## Week 2 : Assignment 2 

1. Which of the following object does not support indexing? 
   <span style="color:#19c5bf">Ans: set</span>
   
2. Given a NumPy array, `arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])`, what is the output of the command, `print(arr[0][1])`?
   <span style="color:#19c5bf">Ans: [4, 5, 6]</span>

In [19]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr[0][1]

array([4, 5, 6])

3. What is th output of the following code ?
   
   ```python
   S = {1, 2, 4, 5} 
   l = []

   for i in range(len(S)):
       l += [1 + i]
   print(l)
   ```
   <span style="color:#19c5bf">Ans: [1, 2, 3, 4]</span>

In [20]:
S = {1, 2, 4, 5} 
l = []

for i in range(len(S)):
    l += [1 + i]
print(l)

[1, 2, 3, 4]


4. What is the output of the following code?
   
   ```python
   import numpy as np
   arr = np.array(np.arange(0, 15))
   print(arr.reshape(3, 5))
   ```
   <span style="color:#19c5bf">Ans: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]</span>

In [21]:
import numpy as np
arr = np.array(np.arange(0, 15))
arr
print(arr.reshape(3, 5)) # 3 rows and 5 columns

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


5. Which of the following code gives output My friend’s house is in Chennai?
   
   <span style="color:#19c5bf">Ans:  
   ```python 
   place = 'Chennai'
   print("My friend’s house is in {}".format(place))
   print("My friend’s house is in {}".format("Chennai"))```
</span>
   

In [22]:
place = 'Chennai'
print("My friend’s house is in {}".format(place))
print("My friend’s house is in {}".format("Chennai"))

My friend’s house is in Chennai
My friend’s house is in Chennai


6. Let 
```python 
t1 = (1, 2, “tuple”, 4)
t2 = (5, 6, 7)
``` 
Which of the following will not give any error after the execution?
   - `t1.append(5)` <span style="color:red">Error as tuple is immutable</span>
   - `x = t2[t1[1]]`
   - `t3 = t1 + t2`
   - `t3 = (t1, t2)`
   - `t3 = (list(t1), list(t2))` 

In [23]:
t1 = (1, 2, 'tuple', 4)
t2 = (5, 6, 7)

# t1.append(5) # Error as tuple is immutable

In [24]:
x = t2[t1[1]] # t1[1] = 2, t2[2] = 7
x

7

In [32]:
t3 = t1 + t2 # (1, 2, 'tuple', 4, 5, 6, 7) is appending t2 to t1 and storing in t3
t3

(1, 2, 'tuple', 4, 5, 6, 7)

In [33]:
t3 = (t1, t2) # ((1, 2, 'tuple', 4), (5, 6, 7)) is storing t1 and t2 in t3
t3

((1, 2, 'tuple', 4), (5, 6, 7))

In [34]:
t3 = (list(t1), list(t2)) # converting t1 and t2 to list and storing in t3
t3 

([1, 2, 'tuple', 4], [5, 6, 7])

7. Let `d = {1 : “Pyhton”, 2 : [1, 2, 3]}`. Which among the following will not give the error after the execution?
   - `d[2].append(4)`   
   - `x = d[0]` <span style="color:red">KeyError: 0</span>
   - `d["one"] = 1`
   - `d.update('one' : 2)`

In [37]:
d = {1 : 'Pyhton', 2 : [1, 2, 3]}

In [39]:
d[2].append(4)
d[2]

[1, 2, 3, 4, 4]

In [45]:
x = d[0]

KeyError: 0

In [41]:
d["one"] = 1
d

{1: 'Pyhton', 2: [1, 2, 3, 4, 4], 'one': 1}

In [44]:
d.update({'one' : 2}) 
d

{1: 'Pyhton', 2: [1, 2, 3, 4, 4], 'one': 2}

8. Which of the following data type is immutable?
   - list
   - set
   - tuple <span style="color:#19c5bf">Ans: tuple is immutable</span>
   - dictionary

9. `student = {‘name’: ‘Jane’, ‘age’: 25, ‘courses’: [‘Math’, ‘Statistics’]}` 
    
    Which among the following will return </br>
    
    `{‘name’: ‘Jane’, ‘age’: 26, ‘courses’: [‘Math’, ‘Statistics’], ‘phone’: ‘123-456’}`
    -  `student.update({‘age’ : 26})`
    -  `student.update({‘age’ : 26, ‘phone’: ‘123-456’})` <span style="color:#19c5bf">Ans</span>
    -  `student['phone'] = ‘123-456’ student.update({‘age’ : 26})` <span style="color:#19c5bf">Ans</span>
    -  None of the above

10. What is the output of the following code?
```python
name = "Mahesh"
l = []
for i in name:
    l.append(i.capitalize())
print(l)
```
<span style="color:#19c5bf">Ans: ['M', 'A', 'H', 'E', 'S', 'H']</span>

In [46]:
name = "Mahesh"
l = []
for i in name:
    l.append(i.capitalize())
print(l)

['M', 'A', 'H', 'E', 'S', 'H']
