# Introduction to Numpy
## Outline
- It is a python package, it stands for numerical python.
- Fundamental package for numerical computations in python
- Supports N-dimensional array objects that can be used for processing muliidimensionl data
- Supports different data-types

## Array and List in Python
- An array is a data structure that stores values of same data type
- List can contain values corresponding to different data types
- Arrays in python can only contain values corresponding to same data type

## Numpy Array
- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.
- The number of dimensions is the rank of the array
- The shape of an array is a tuple of integers giving the size of the array along each dimension

## Creation of Array

In [2]:
my_list = [1, 2, 3, 4, 5, 6] 

In [5]:
import numpy as np
my_array = np.array(my_list, dtype = int)
print(my_array)

[1 2 3 4 5 6]


In [9]:
print(type(my_array))
print(len(my_array))
print(my_array.shape)
print(my_array.ndim)

<class 'numpy.ndarray'>
6
(6,)
1


In [11]:
array2 = my_array.reshape(3,2)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [12]:
array3 = my_array.reshape(3,-1) # -1 means that numpy will figure out the number of columns
print(array3)
print(array3.shape)
print(array3.ndim) #

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2


In [16]:
# Initializing numpy arrays from nested python lists
my_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_list3 = [[92, 93, 94], [95, 96, 97], [98, 99, 100]]
my_list4 = [[43, 44, 45], [46, 47, 48], [49, 50, 51]]

mul_array = np.array([my_list2, my_list3, my_list4])
print(mul_array)
print(mul_array.shape) 

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 92  93  94]
  [ 95  96  97]
  [ 98  99 100]]

 [[ 43  44  45]
  [ 46  47  48]
  [ 49  50  51]]]
(3, 3, 3)


In [17]:
mul_array.flatten() # flattens the array to a single dimension

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  92,  93,  94,  95,
        96,  97,  98,  99, 100,  43,  44,  45,  46,  47,  48,  49,  50,
        51])

## Numpy-Attributes
NumPy arrays come with several attributes that provide useful information about the array. Here are some of the most commonly used attributes:

1. **`ndarray.ndim`**:
   - The number of dimensions (axes) of the array.
   ```python
   import numpy as np
   a = np.array([[1, 2, 3], [4, 5, 6]])
   print(a.ndim)  # Output: 2
   ```

2. **`ndarray.shape`**:
   - The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.
   ```python
   print(a.shape)  # Output: (2, 3)
   ```

3. **`ndarray.size`**:
   - The total number of elements in the array.
   ```python
   print(a.size)  # Output: 6
   ```

4. **`ndarray.dtype`**:
   - The data type of the elements in the array.
   ```python
   print(a.dtype)  # Output: int64 (or int32 depending on the system)
   ```

5. **`ndarray.itemsize`**:
   - The size in bytes of each element in the array.
   ```python
   print(a.itemsize)  # Output: 8 (for int64)
   ```

6. **`ndarray.nbytes`**:
   - The total number of bytes consumed by the elements of the array.
   ```python
   print(a.nbytes)  # Output: 48 (6 elements * 8 bytes each)
   ```

7. **`ndarray.T`**:
   - The transposed array.
   ```python
   print(a.T)
   # Output:
   # [[1 4]
   #  [2 5]
   #  [3 6]]
   ```

8. **`ndarray.real`**:
   - The real part of the array elements (useful for complex numbers).
   ```python
   b = np.array([1+2j, 3+4j])
   print(b.real)  # Output: [1. 3.]
   ```

9. **`ndarray.imag`**:
   - The imaginary part of the array elements (useful for complex numbers).
   ```python
   print(b.imag)  # Output: [2. 4.]
   ```

10. **`ndarray.flat`**:
    - A 1-D iterator over the array.
    ```python
    for element in a.flat:
        print(element)
    # Output: 1 2 3 4 5 6
    ```

11. **`ndarray.ctypes`**:
    - An object to simplify the interaction of the array with C code.
    ```python
    print(a.ctypes)
    ```

These attributes provide a wealth of information about the structure and properties of NumPy arrays, making it easier to manipulate and understand the data they contain.